### ISSUE TITLE
Quant 2 Assignment

### ISSUE THREAD

**Issue by mggetts** [SES-5215-F2020/mgetts-quant#2]
I realized mid lecture a) that I hadn't submitted my issue and b) why my summary text wasn't working on my histograms, so I re-uploaded my files after making that quick change in each histogram.

**Comment by saratepfer** [comment]
Thank you, Marissa! Nice job. No need to assign Catherine to the issue, as she won't be doing any grading. You can just assign Carole and I. Please see a few comments on code and content below:

**Comments on code**
- Line 11: replace {r} with {r, message = FALSE} to prevent library messages from cluttering your knitted markdown file.
- The gaps in your histograms are due to the binwidth being set at 30. Try tweaking the binwidth (i recommend using smaller values) to refine your histograms/remove the gaps.
- Your code seems to be missing the analysis for the categorical variables. Was this intentional? We are looking to see the proportions for each category and the corresponding 95% confidence intervals, both of which can be found using a t-test. (See Catherine's example assignment for details.) If you would like to add this to your assignment and get feedback on it, feel free to open another issue or reopen this one.

**Comments on content**
- Great job calculating the different descriptive statistics. Please accompany your calculations with interpretations of your findings. It would also be helpful if the outputs were formatted or tabulated in some way to help with clarity. In its current form, the reader is asked to go through raw R outputs to find certain statistics (e.g., 95% confidence interval). (See Catherine's example assignment for a way to do the formatting and interpretation, either within or outside of R.)
