### ISSUE TITLE
Assignment 5 

### ISSUE THREAD

**Issue by mggetts** [SES-5215-F2020/mgetts-quant#5]
I think I did a couple of funky things with my data so I'm really hoping I interpreted it right! I may check with a classmate or two in the morning and make a couple of minor changes before I officially submit. But fingers crossed I was right :) 

https://ses-5215-f2020.github.io/mgetts-quant/Quant5.html
https://ses-5215-f2020.github.io/mgetts-quant/Quant5.Rmd

**Comment by c-voulgaris** [comment]
Good work.

Transforming the dependent variable is fine/valid - as long as you aren't totally changing the thing you're predicting.

In `logmodel3` and `logmodel4`, you aren't log-transforming income anymore, which would explain why the R-square value drops back down to closer to what you were seeing for the initial model.

On your model with the interaction terms - when you include an interaction between two variables, you should include each of those variables separately as well (unless you have a really strong reason not to). In this particular case, since you didn't do that, it's treating the combination of laptop and internet access as one categorical variable. With a categorical variable, there always needs to be an omitted category (your base case that you're comparing everything to) - so R has selected YesInternet/YesLaptop as your base case and dropped it from the model (which is why there's an NA value for that coefficient.

That NA in your coefficient table will cause you trouble when you try to create some of the figures like the ones in the tutorial. If you wanted to, you could recreate what you done (I think) by accident and do it on purpose by creating a single categorical variable to describe the combination of laptop and internet. OR (and this is what I would suggest) you could just add laptop and internet as separate variables in addition to the interaction term. 

You haven't explicitly identified any of your models as your preferred model.
